### ISSUE TITLE
Use of swap_index parameter

### ISSUE THREAD

**Issue by AmarBouali** [AliaksandrSiarohin/motion-cosegmentation#10]
Hello Aliaksander,

Thanks a lot for providing this code that would like to experiment.
Could ou explain the use of the swap_index parameter in the part_swap.py script ?
How the index values relate to parts and how to use them in particular with the different vox-* checkpoints ?

**Comment by AliaksandrSiarohin** [comment]
There is a visualization of parts and indexes in colab notebook. You can refer to this visualizations to see which index correspond to which part.

**Comment by AmarBouali** [comment]
> There is a visualization of parts and indexes in colab notebook. You can refer to this visualizations to see which index correspond to which part.

Excellent. Thanks !
