### ISSUE TITLE
Epochs\repeats number for saved checkpoints

### ISSUE THREAD

**Issue by marlon-br** [AliaksandrSiarohin/motion-cosegmentation#12]
Hello Aliaksandr,

For the checkpoints stored on Drive, especially:
vox-first-order.pth.tar
vox-10segments.pth.tar
For how many epochs\repeats the models were trained?

**Comment by AliaksandrSiarohin** [comment]
100\75 for first order 10\75 for coseg.

**Comment by marlon-br** [comment]
Thanks! Could you please share the checkpoints that you mentioned in your article? That one, that were trained for 10000 epochs

**Comment by AliaksandrSiarohin** [comment]
In the paper number of iterations is reported, 10k correspond to 100\75

**Comment by marlon-br** [comment]
Do you happen to have something similar for coseg by hand? Trained for more than 10/75

**Comment by AliaksandrSiarohin** [comment]
Didn't get you question.

**Comment by AliaksandrSiarohin** [comment]
Sorry 10k correspond to 10/75. 100k  is 100/75

**Comment by marlon-br** [comment]
I see, thanks! Do you think it is worth to train both models for more iterations? Could more training on the same data set from "video-processing" be useful?

**Comment by AliaksandrSiarohin** [comment]
First order is worth training. Coseg I tried, but this seem more or less optimal.

**Comment by marlon-br** [comment]
In my current environment inference is done on Tesla K80 GPU and it takes about 150 ms for one image. Do you have an idea how to make it faster?
