### ISSUE TITLE
Unable to download weights

### ISSUE THREAD

**Issue by Mohamed209** [AliaksandrSiarohin/motion-cosegmentation#19]
trying to download `vox-first-order.pth.tar` from https://drive.google.com/open?id=1SsBifjoM_qO0iFzb8wLlsz_4qW2j8dZe , but google drive issues this message 
`Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
administrator.`

**Comment by AliaksandrSiarohin** [comment]
Try yandex disk.

**Comment by Mohamed209** [comment]
Is there any intention to refresh Google drive link , this will make our development more smooth than using Yandex

**Comment by AliaksandrSiarohin** [comment]
There are at least 2 link to google drive, another is this one https://drive.google.com/drive/folders/1PyQJmkdCsAkOYwUyaj_l-l0as-iLDgeH?usp=sharing
It is not possible to create a new link every time there are overflow.

**Comment by Mohamed209** [comment]
Ok , I will check the other link

**Comment by Mohamed209** [comment]
@AliaksandrSiarohin  , i am targeting motion-cosegmentation checkpoints `vox-first-order.pth.tar` , not first order model weights

**Comment by AliaksandrSiarohin** [comment]
There is no difference between these two.
