### ISSUE TITLE
cannot use part_swap.py along with --supervised in my trained model

### ISSUE THREAD

**Issue by xiuyangleiasp** [AliaksandrSiarohin/motion-cosegmentation#23]
Hi @AliaksandrSiarohin !
Thanks for sharing such an awesome work.
I've trained model with my own dataset. with config/vox-256-sem-15segments.yaml
and **It's worked with** command:
`part_swap.py --config config/vox-256-sem-15segments.yaml --checkpoint log/vox-256-sem-15segments\ 26-08-20\ 07\:56\:19/00000000-checkpoint.pth.tar --source_image 2.jpg --target_video 2.mp4 --swap_index 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14`
however got errors with command:
`part_swap.py --config config/vox-256-sem-15segments.yaml --checkpoint log/vox-256-sem-15segments\ 26-08-20\ 07\:56\:19/00000000-checkpoint.pth.tar --source_image 2.jpg --target_video 2.mp4 --swap_index 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14 --supervised
`
![image](https://user-images.githubusercontent.com/9282338/91278150-6dc65500-e7b6-11ea-803f-d20627a9c095.png)

Can you please help me with this ?
Thanks

**Comment by AliaksandrSiarohin** [comment]
Same happens with my checkpoints? Probably a bug. Try to commend this line https://github.com/AliaksandrSiarohin/motion-cosegmentation/blob/f4c2683c7163935e4f0c88b01c45ed9da18391fe/logger.py#L26

**Comment by xiuyangleiasp** [comment]
> Same happens with my checkpoints? 
>work correctly with your checkpoint.
Probably a bug. Try to commend this line https://github.com/AliaksandrSiarohin/motion-cosegmentation/blob/f4c2683c7163935e4f0c88b01c45ed9da18391fe/logger.py#L26
> It worked. Thanks for your reply

**Comment by xiuyangleiasp** [comment]
> > Same happens with my checkpoints?
> > work correctly with your checkpoint.
> > Probably a bug. Try to commend this line https://github.com/AliaksandrSiarohin/motion-cosegmentation/blob/f4c2683c7163935e4f0c88b01c45ed9da18391fe/logger.py#L26
> > 
> > It worked. Thanks for your reply
