### ISSUE TITLE
output video from partswap.py is very blurry

### ISSUE THREAD

**Issue by Mohamed209** [AliaksandrSiarohin/motion-cosegmentation#24]
check attached image , output of face swap is very blurry (image taken from video)
the question is does this relate to networks (segmentation network or generator) operations , or relates to frame post or pre-processing after model predictions

![Screenshot_2020-08-27_02-18-26](https://user-images.githubusercontent.com/12018493/91369503-37b3c000-e80c-11ea-8503-483bb9e27b9c.png)

In other words , how can I get higher resolution results

**Comment by AliaksandrSiarohin** [comment]
What is the input source?

**Comment by Mohamed209** [comment]
> What is the input source?

here is original target video : https://drive.google.com/file/d/1QSEECWaH3J-KrYV1CG13at7t92tIIkE_/view?usp=sharing
and input source : https://drive.google.com/file/d/1DWAvcKoVCGOaM1Ywoa6ulsCTQu8QqMQD/view?usp=sharing

I have also checked all post-processing steps , i think resolution loss happens in model predictions stage !

**Comment by AliaksandrSiarohin** [comment]
Try to crop the target video, it is too large probably.

**Comment by Mohamed209** [comment]
> Try to crop the target video, it is too large probably.

shall this script crop desired speaker face in all video frames to generate smaller version of the original video !

https://github.com/AliaksandrSiarohin/first-order-model/blob/master/crop-video.py

**Comment by AliaksandrSiarohin** [comment]
Yes.
