### ISSUE TITLE
Could you please provided the ground truth of foreground evaluation？

### ISSUE THREAD

**Issue by Talegqz** [AliaksandrSiarohin/motion-cosegmentation#32]
Thanks！

**Comment by roysubhankar** [comment]
Hi, you can find the ground truth for the vox-celeb dataset in this folder https://drive.google.com/drive/folders/18l3W4tkYWnpPcwMMhy07Tc6R7Ky_ouoJ?usp=sharing. The file is called vox-test-masks.tar.gz

**Comment by Talegqz** [comment]
Thanks for your help！

**Comment by Talegqz** [comment]
@roysubhankar hi，could you please the ground truth for taichi-hd? Thanks for your help!

**Comment by roysubhankar** [comment]
done.
