### ISSUE TITLE
First Order Motion Model based alignment ??

### ISSUE THREAD

**Issue by instant-high** [AliaksandrSiarohin/motion-cosegmentation#46]
Hello Aliaksadr, me again.

What's the use of "First Order Motion Model based alignment"?
I can't get it to work. It gives me following errors:

missing 5 required positional arguments: 'block_expansion', 'num_blocks', 'max_features', 'num_kp', and 'num_channels'

This is an example of my commandline (working when i don't use "--first_order_motion_model" option)

python demo.py --config c:\tutorial\first-order-model/config/vox-256-sem-5segments.yaml --target_video "D:\Temp\ich2.mp4" --source_image "D:\Temp\attila.jpg" --result_video "D:\Temp\00super_Swap.mp4" --checkpoint c:\tutorial\first-order-model/checkpoints/vox-5segments.pth.tar --swap_index 1,2,5 --supervised --first_order_motion_model

Which corresponding checkpoint do you mean?

I hope you can help me...

**Comment by AliaksandrSiarohin** [comment]
You should use config with 10 regions.
