### ISSUE TITLE
pretrained tar does not look like a tar archive

### ISSUE THREAD

**Issue by youngjung** [AliaksandrSiarohin/motion-cosegmentation#6]
Hi,
Thanks for sharing nice work.

I downloaded the pretrained checkpoints from google drive but they do not look like a tar archive.

command
`$ tar -xf vox-10segments.pth.tar`

message (linux)
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

message (mac)
```
tar: Error opening archive: Unrecognized archive format
```

FYI (linux)
```
$ tar --version
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

FYI (mac)
```
tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
```

`vox-15segments.pth.tar` gave me the same error.

Could you check the files?
Has anyone found the same issue?

**Comment by AliaksandrSiarohin** [comment]
It is not archive. You should use 
```- - checkpoint vox-15segments.pth.tar ````

**Comment by youngjung** [comment]
That's wow. I thought it is a tarball because its extension is tar.
It works, thank you :)
