### ISSUE TITLE
First Order Motion Model

### ISSUE THREAD

**Issue by growbettereyes** [AliaksandrSiarohin/motion-cosegmentation#8]
Thanks so much for maintaining this!

I've been trying to use the First Order Motion Model

python part_swap.py --config /home/growbettereyes/motion-cosegmentation-master/config/vox-256-sem-15segments.yaml   --target_video /home/growbettereyes/materials_for_testing/somany2.mp4  --source_image /home/growbettereyes/materials_for_testing/26.png --checkpoint /home/growbettereyes/motion-cosegmentation-master/vox-first-order.pth.tar  --swap_index 0,1 --supervised --first_order_motion_model

 and I keep getting this error:

  File "part_swap.py", line 230, in <module>
    first_order_motion_model=opt.first_order_motion_model, cpu=opt.cpu)
  File "part_swap.py", line 126, in load_checkpoints
    load_segmentation_module(segmentation_module, checkpoint)
  File "/home/growbettereyes/motion-cosegmentation-master/logger.py", line 35, in load_segmentation_module
    module.state_dict()['affine.weight'].copy_(checkpoint['kp_detector']['jacobian.weight'])
RuntimeError: The expanded size of the tensor (60) must match the existing size (40) at non-singleton dimension 0.  Target sizes: [60, 35, 7, 7].  Tensor sizes: [40, 35, 7, 7]

I've scaled all the images to the recommended sizes, checked my pytorch installation was 1.0.0, tried with several different sources of both kinds. Am I using the right config?

Ps. the readme says the argument is "--first-order-motion-model" but its "--first_order_motion_model"

**Comment by AliaksandrSiarohin** [comment]
You should use 10 segments config.

**Comment by growbettereyes** [comment]
That worked great, Thank you!

**Comment by dllafer** [comment]
Is it possible to use the 15 segements config?
