### ISSUE TITLE
Is there a function for whole-face swap?

### ISSUE THREAD

**Issue by HelixNGC7293** [AliaksandrSiarohin/motion-cosegmentation#9]
Hello Aliaksandr!

Thank you for your project!~
I'm new to python, just wondering if your project has a .py file or function for whole-face swap? 
And is there an instruction for the swap_index function? That'd be pretty awesome!

Thank you so much!

**Comment by AliaksandrSiarohin** [comment]
```
python part_swap.py --source_image ... --target_video ... --checkpoint vox-first-order.pth.tar --config config/vox-256-10segments.yaml --supervised --first_order_motion_model  
```
See colab notebook for visualization of swap index. For face swap it should be 
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 if I remember correctly.

**Comment by HelixNGC7293** [comment]
Thank you!! It works!~
